### ISSUE TITLE
Block Type - Text

### ISSUE THREAD

**Issue by mateusKoppe** [mateusKoppe/basenote#12]
Implement restful resource to manage text blocks, and basic text block UI.

---
**Estimate:** 2h

#### Execution time
 - **Development:** 31/08 20:30 – 22:30, 31/08 20:00 – 21:00
 - **Issues found:** (fazer registro completo dos bugs
no arquivo do Sprint Backlog)
 - **Tester:** name - start-date – end-date
- **Rework:** name - start-date – end-date

**Comment by arufonsekun** [comment]
Essa _issue_ não foi desenvolvida no dia 10/08 devido sua dependência das issues #6 e #5, ao invés disso a issue #11 foi desenvolvida em seu lugar.
